# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ashddev@proton.me
author_name: Ash Daly
contract_name: election
deployment_language: python
preset_name: starter
project_name: algorank

